USE sys;

CREATE DATABASE ProyectoCrud;

USE ProyectoCrud;

CREATE TABLE Clientes(

ID INT NOT NULL,
Cliente VARCHAR(50) NOT NULL,
Telefono VARCHAR(12),
Mail VARCHAR(50) NOT NULL,

CONSTRAINT PK_CLIENTES PRIMARY KEY (ID)
);

CREATE TABLE Ventas(

ID INT NOT NULL,
ID_Cliente INT NOT NULL,
Fecha DATE,
Total DECIMAL (8,2) DEFAULT 0.00,

CONSTRAINT PK_VENTAS PRIMARY KEY (ID)
);


CREATE TABLE Productos(

ID INT NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Precio DECIMAL (8,2) DEFAULT 0.00,
Categoria VARCHAR(50),

CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID)
);


CREATE TABLE DetalleVenta(

ID INT NOT NULL,
ID_Venta INT NOT NULL,
ID_Producto INT NOT NULL,
PrecioUnitario DECIMAL (8,2) NOT NULL,
Cantidad INT NOT NULL DEFAULT 0.00,
PrecioTotal DECIMAL (8,2) NOT NULL,

CONSTRAINT PK_DETALLEVENTA PRIMARY KEY (ID)
);


/*CREANDO LAS CLAVES FORANEAS*/

ALTER TABLE Ventas ADD CONSTRAINT FK_CLIENTES_VENTAS FOREIGN KEY (ID_Cliente) REFERENCES Clientes (ID);

ALTER TABLE DetalleVenta ADD CONSTRAINT FK_DETALLEVENTA_VENTA FOREIGN KEY (ID_Venta) REFERENCES Ventas (ID);

ALTER TABLE DetalleVenta ADD CONSTRAINT FK_DETALLEVENTA_PRODUCTO FOREIGN KEY (ID_Producto) REFERENCES Productos (ID);


